from __future__ import annotations

import re
from dataclasses import asdict
from typing import Any

from cloud_agent_service.models import HarnessCategory, HarnessSpec

CUSTOM_HARNESS_PREFIX = "custom:"
CUSTOM_HARNESS_RE = re.compile(r"^custom:[a-z0-9][a-z0-9_.-]{1,63}$")


LOCAL_TEMPLATE_HARNESS = HarnessSpec(
    harness_id="local-template",
    name="Local Deterministic Template Harness",
    category=HarnessCategory.CUSTOM,
    rank=None,
    provider="cloud-agent-service",
    runtime="python-standard-library",
    execution_contract="local-deterministic-edit.v1",
    repo_url=None,
    docs_url="local://cloud-agent-service/harnesses/local-template",
    install_hint="built in",
    env_requirements=[],
    strengths=["offline deterministic smoke path", "stable tests", "no external secrets"],
    integration_notes=[
        "Default harness for local MVP proof.",
        "Use top-20 or custom harness IDs to hand workers a different runtime contract.",
    ],
)


INDEXED_AGENT_HARNESSES: list[HarnessSpec] = [
    HarnessSpec(
        harness_id="factory-droid",
        name="Factory Droid",
        category=HarnessCategory.CODING_CLI,
        rank=1,
        provider="factory-ai",
        runtime="node-cli-and-managed-platform",
        execution_contract="repo-coding-cli.v1",
        repo_url="https://github.com/factory-ai/factory",
        docs_url="https://docs.factory.ai/",
        install_hint="install Droid CLI in the worker image or dispatch to Factory platform",
        env_requirements=["Factory auth or provider key"],
        strengths=[
            "terminal benchmark performance",
            "CLI/Web/Slack/Teams workflows",
            "agent-native SDLC",
        ],
        integration_notes=[
            "High-priority adapter candidate because it is purpose-built for repo work.",
            "Factory reports Droid at the top of Terminal-Bench; verify exact benchmark "
            "version before using it as a promotion claim.",
        ],
    ),
    HarnessSpec(
        harness_id="openai-codex-cli",
        name="OpenAI Codex CLI",
        category=HarnessCategory.CODING_CLI,
        rank=2,
        provider="openai",
        runtime="node-cli",
        execution_contract="repo-coding-cli.v1",
        repo_url="https://github.com/openai/codex",
        docs_url="https://github.com/openai/codex",
        install_hint="install Codex CLI in the worker image or use a derived worker image",
        env_requirements=["OPENAI_API_KEY or ChatGPT auth runtime"],
        strengths=["terminal coding agent", "repo editing", "MCP-capable workflow"],
        integration_notes=["Run only in isolated workspaces with explicit command policy."],
    ),
    HarnessSpec(
        harness_id="claude-code",
        name="Claude Code",
        category=HarnessCategory.CODING_CLI,
        rank=3,
        provider="anthropic",
        runtime="node-cli",
        execution_contract="repo-coding-cli.v1",
        repo_url="https://github.com/anthropics/claude-code",
        docs_url="https://platform.claude.com/docs/en/home",
        install_hint="install Claude Code CLI in the worker image",
        env_requirements=["ANTHROPIC_API_KEY or Claude Code auth runtime"],
        strengths=["terminal agent", "git workflows", "large codebase navigation"],
        integration_notes=["Requires provider-specific auth and workspace isolation."],
    ),
    HarnessSpec(
        harness_id="pi-coding-agent",
        name="Pi Coding Agent",
        category=HarnessCategory.CODING_CLI,
        rank=4,
        provider="earendil-works",
        runtime="node-cli-sdk-rpc",
        execution_contract="repo-coding-cli.v1",
        repo_url="https://github.com/earendil-works/pi/tree/main/packages/coding-agent",
        docs_url="https://pi.dev/docs/latest",
        install_hint="install @earendil-works/pi-coding-agent in the worker image",
        env_requirements=["model provider key or provider subscription auth"],
        strengths=[
            "minimal terminal harness",
            "skills/extensions/packages",
            "print/JSON/RPC/SDK modes",
        ],
        integration_notes=[
            "Strong fit for custom harness labs because it is designed to be extended.",
            "Use print or RPC mode for non-interactive worker adapters.",
        ],
    ),
    HarnessSpec(
        harness_id="hermes-agent",
        name="Hermes Agent",
        category=HarnessCategory.ORCHESTRATION_RUNTIME,
        rank=5,
        provider="nous-research",
        runtime="python-cli-gateway",
        execution_contract="long-running-agent-harness.v1",
        repo_url="https://github.com/nousresearch/hermes-agent",
        docs_url="https://hermes-agent.nousresearch.com/",
        install_hint="install Hermes Agent in the worker image or run it as a gateway service",
        env_requirements=["model provider key"],
        strengths=[
            "persistent memory",
            "self-improving skills",
            "subagents and multiple terminal backends",
        ],
        integration_notes=[
            "Best fit for durable agent labs and long-running cloud workers.",
            "Treat messaging gateways separately from repo-edit execution permissions.",
        ],
    ),
    HarnessSpec(
        harness_id="gemini-cli",
        name="Gemini CLI",
        category=HarnessCategory.CODING_CLI,
        rank=6,
        provider="google",
        runtime="node-cli",
        execution_contract="repo-coding-cli.v1",
        repo_url="https://github.com/google-gemini/gemini-cli",
        docs_url="https://developers.google.com/gemini-code-assist/docs/gemini-cli",
        install_hint="install @google/gemini-cli in the worker image",
        env_requirements=["GEMINI_API_KEY or Google auth runtime"],
        strengths=["terminal AI agent", "codebase queries", "Google model integration"],
        integration_notes=["Best wrapped behind a non-interactive command adapter."],
    ),
    HarnessSpec(
        harness_id="github-copilot-cloud-agent",
        name="GitHub Copilot Cloud Agent",
        category=HarnessCategory.CLOUD_CODING_AGENT,
        rank=7,
        provider="github",
        runtime="github-actions-cloud-agent",
        execution_contract="managed-cloud-agent.v1",
        repo_url=None,
        docs_url="https://docs.github.com/en/copilot/concepts/agents/cloud-agent/about-cloud-agent",
        install_hint="configure GitHub Copilot cloud agent access for the target repo",
        env_requirements=["GitHub Copilot plan and repository enablement"],
        strengths=["ephemeral dev environment", "GitHub-native PR workflow", "paid plan support"],
        integration_notes=["Dispatch through GitHub APIs rather than local shell execution."],
    ),
    HarnessSpec(
        harness_id="google-jules",
        name="Google Jules",
        category=HarnessCategory.CLOUD_CODING_AGENT,
        rank=8,
        provider="google",
        runtime="managed-cloud-vm",
        execution_contract="managed-cloud-agent.v1",
        repo_url="https://github.com/google-labs-code/jules-action",
        docs_url="https://jules.google/docs/",
        install_hint="use Jules UI/API/action when available for the target account",
        env_requirements=["Jules account access"],
        strengths=["async coding tasks", "GitHub integration", "cloud VM execution"],
        integration_notes=["Treat as managed handoff; do not claim local execution."],
    ),
    HarnessSpec(
        harness_id="openhands",
        name="OpenHands",
        category=HarnessCategory.CLOUD_CODING_AGENT,
        rank=9,
        provider="openhands",
        runtime="python-service-or-container",
        execution_contract="repo-coding-service.v1",
        repo_url="https://github.com/OpenHands/OpenHands",
        docs_url="https://openhands.dev/",
        install_hint="install or run OpenHands worker/server in the agent container",
        env_requirements=["model provider key"],
        strengths=["cloud coding agents", "SDK", "ephemeral workspaces"],
        integration_notes=["Strong fit for ECS/Kubernetes-backed repo workspaces."],
    ),
    HarnessSpec(
        harness_id="open-swe",
        name="Open SWE",
        category=HarnessCategory.CLOUD_CODING_AGENT,
        rank=10,
        provider="langchain",
        runtime="langgraph-cloud-agent",
        execution_contract="managed-or-self-hosted-coding-agent.v1",
        repo_url="https://github.com/langchain-ai/open-swe",
        docs_url="https://www.langchain.com/blog/open-swe-an-open-source-framework-for-internal-coding-agents",
        install_hint="deploy Open SWE service or call a hosted Open SWE endpoint",
        env_requirements=["model provider key", "GitHub app credentials"],
        strengths=["async coding agent", "PR creation", "subagent orchestration"],
        integration_notes=["Built on LangGraph; useful as a cloud-native reference harness."],
    ),
    HarnessSpec(
        harness_id="swe-agent",
        name="SWE-agent",
        category=HarnessCategory.CODING_CLI,
        rank=11,
        provider="swe-agent",
        runtime="python-cli",
        execution_contract="repo-coding-cli.v1",
        repo_url="https://github.com/SWE-agent/SWE-agent",
        docs_url="https://swe-agent.com/latest/",
        install_hint="install swe-agent in the worker image",
        env_requirements=["model provider key"],
        strengths=["GitHub issue repair", "SWE-bench focus", "research-friendly configs"],
        integration_notes=["Prefer issue/task fixtures and deterministic config files."],
    ),
    HarnessSpec(
        harness_id="aider",
        name="Aider",
        category=HarnessCategory.CODING_CLI,
        rank=12,
        provider="aider",
        runtime="python-cli",
        execution_contract="repo-coding-cli.v1",
        repo_url="https://github.com/Aider-AI/aider",
        docs_url="https://aider.chat/docs/",
        install_hint="install aider-chat in the worker image",
        env_requirements=["model provider key"],
        strengths=["terminal pair programming", "git-aware edits", "many language support"],
        integration_notes=["Use non-interactive prompts and capture generated commits/diffs."],
    ),
    HarnessSpec(
        harness_id="cline",
        name="Cline",
        category=HarnessCategory.CODING_CLI,
        rank=13,
        provider="cline",
        runtime="node-cli-or-sdk",
        execution_contract="repo-coding-cli.v1",
        repo_url="https://github.com/cline/cline",
        docs_url="https://cline.bot/",
        install_hint="install Cline CLI/SDK in the worker image when headless mode is available",
        env_requirements=["model provider key"],
        strengths=["terminal workflows", "MCP integration", "plan/act modes"],
        integration_notes=["Validate headless mode before enabling unattended runs."],
    ),
    HarnessSpec(
        harness_id="goose",
        name="Goose",
        category=HarnessCategory.CODING_CLI,
        rank=14,
        provider="block",
        runtime="rust-cli-api",
        execution_contract="repo-coding-cli.v1",
        repo_url="https://github.com/aaif-goose/goose",
        docs_url="https://goose-docs.ai/",
        install_hint="install goose CLI/API in the worker image",
        env_requirements=["model provider key"],
        strengths=["CLI and API", "automation", "MCP-oriented extensibility"],
        integration_notes=["Good candidate for a CLI adapter plus event capture."],
    ),
    HarnessSpec(
        harness_id="openai-agents-sdk",
        name="OpenAI Agents SDK",
        category=HarnessCategory.AGENT_SDK,
        rank=15,
        provider="openai",
        runtime="python-or-typescript-sdk",
        execution_contract="agent-sdk.v1",
        repo_url="https://github.com/openai/openai-agents-python",
        docs_url="https://developers.openai.com/api/docs/guides/agents",
        install_hint="install openai-agents in the worker image",
        env_requirements=["OPENAI_API_KEY"],
        strengths=["multi-agent workflows", "tool use", "provider-agnostic SDK"],
        integration_notes=["Use for service-owned orchestration, not raw repo shell edits."],
    ),
    HarnessSpec(
        harness_id="langgraph",
        name="LangGraph",
        category=HarnessCategory.ORCHESTRATION_RUNTIME,
        rank=16,
        provider="langchain",
        runtime="python-or-typescript-sdk",
        execution_contract="agent-sdk.v1",
        repo_url="https://github.com/langchain-ai/langgraph",
        docs_url="https://docs.langchain.com/oss/python/langgraph/overview",
        install_hint="install langgraph in the worker image",
        env_requirements=["model provider key"],
        strengths=["stateful agents", "long-running workflows", "human-in-the-loop"],
        integration_notes=["Use for durable orchestration around repo-edit tools."],
    ),
    HarnessSpec(
        harness_id="microsoft-agent-framework",
        name="Microsoft Agent Framework",
        category=HarnessCategory.AGENT_SDK,
        rank=17,
        provider="microsoft",
        runtime="python-or-dotnet-sdk",
        execution_contract="agent-sdk.v1",
        repo_url="https://github.com/microsoft/agent-framework",
        docs_url="https://learn.microsoft.com/en-us/agent-framework/",
        install_hint="install Microsoft Agent Framework dependencies in worker image",
        env_requirements=["model provider key"],
        strengths=["production-grade agents", "multi-language support", "workflows"],
        integration_notes=["Prefer over legacy AutoGen for new Microsoft-oriented builds."],
    ),
    HarnessSpec(
        harness_id="google-adk",
        name="Google Agent Development Kit",
        category=HarnessCategory.AGENT_SDK,
        rank=18,
        provider="google",
        runtime="python-sdk",
        execution_contract="agent-sdk.v1",
        repo_url="https://github.com/google/adk-python",
        docs_url="https://adk.dev/",
        install_hint="install google-adk in the worker image",
        env_requirements=["Google model or Vertex auth"],
        strengths=["agent build/evaluate/deploy loop", "Google Cloud deployment", "tooling"],
        integration_notes=["Good fit when Mirendil wants model lab eval loops on GCP too."],
    ),
    HarnessSpec(
        harness_id="strands-agents",
        name="Strands Agents",
        category=HarnessCategory.AGENT_SDK,
        rank=19,
        provider="aws",
        runtime="python-or-typescript-sdk",
        execution_contract="agent-sdk.v1",
        repo_url="https://github.com/strands-agents/harness-sdk",
        docs_url="https://strandsagents.com/docs/user-guide/quickstart/overview/",
        install_hint="install Strands Agents SDK in worker image",
        env_requirements=["AWS or model provider auth"],
        strengths=["AWS-native path", "model-driven agents", "Python and TypeScript SDKs"],
        integration_notes=["Strong AWS/ECS alignment for this repo's assumed cloud target."],
    ),
    HarnessSpec(
        harness_id="pydantic-ai",
        name="Pydantic AI",
        category=HarnessCategory.AGENT_SDK,
        rank=20,
        provider="pydantic",
        runtime="python-sdk",
        execution_contract="agent-sdk.v1",
        repo_url="https://github.com/pydantic/pydantic-ai",
        docs_url="https://pydantic.dev/docs/ai/overview/",
        install_hint="install pydantic-ai in the worker image",
        env_requirements=["model provider key"],
        strengths=["typed outputs", "production Python ergonomics", "eval-friendly contracts"],
        integration_notes=["High fit for schema-first agent outputs and promotion gates."],
    ),
    HarnessSpec(
        harness_id="crewai",
        name="CrewAI",
        category=HarnessCategory.AGENT_SDK,
        rank=22,
        provider="crewai",
        runtime="python-sdk",
        execution_contract="agent-sdk.v1",
        repo_url="https://github.com/crewAIInc/crewAI",
        docs_url="https://crewai.com/open-source",
        install_hint="install crewai in the worker image",
        env_requirements=["model provider key"],
        strengths=["multi-agent roles", "task orchestration", "enterprise adoption"],
        integration_notes=["Useful for role-specialized agents around repo changes."],
    ),
    HarnessSpec(
        harness_id="llamaindex",
        name="LlamaIndex",
        category=HarnessCategory.AGENT_SDK,
        rank=23,
        provider="llamaindex",
        runtime="python-or-typescript-sdk",
        execution_contract="agent-sdk.v1",
        repo_url="https://github.com/run-llama/llama_index",
        docs_url="https://www.llamaindex.ai/",
        install_hint="install llama-index in the worker image",
        env_requirements=["model provider key"],
        strengths=["document/code indexing", "agent workflows", "retrieval-heavy tasks"],
        integration_notes=["Best for repo understanding, memory, and RAG-heavy harnesses."],
    ),
    HarnessSpec(
        harness_id="agno",
        name="Agno",
        category=HarnessCategory.ORCHESTRATION_RUNTIME,
        rank=21,
        provider="agno",
        runtime="python-sdk-and-runtime",
        execution_contract="agent-platform-runtime.v1",
        repo_url="https://github.com/agno-agi/agno",
        docs_url="https://docs.agno.com/",
        install_hint="install agno or run AgentOS alongside the worker",
        env_requirements=["model provider key"],
        strengths=["agent platform runtime", "tracing/RBAC", "any-framework management"],
        integration_notes=["Directly aligned with any-harness control-plane support."],
    ),
]


class HarnessRegistry:
    def __init__(self, harnesses: list[HarnessSpec] | None = None) -> None:
        all_harnesses = [LOCAL_TEMPLATE_HARNESS, *(harnesses or INDEXED_AGENT_HARNESSES)]
        self._harnesses = {harness.harness_id: harness for harness in all_harnesses}

    def get(self, harness_id: str) -> HarnessSpec:
        harness_id = harness_id.strip()
        if harness_id in self._harnesses:
            return self._harnesses[harness_id]
        if CUSTOM_HARNESS_RE.fullmatch(harness_id):
            return self._custom_harness(harness_id)
        raise KeyError(harness_id)

    def list(self, include_local: bool = True) -> list[HarnessSpec]:
        harnesses = sorted(
            self._harnesses.values(),
            key=lambda harness: (
                harness.rank is None,
                harness.rank or 10_000,
                harness.harness_id,
            ),
        )
        if include_local:
            return harnesses
        return [harness for harness in harnesses if harness.rank is not None]

    def top(self, limit: int = 20) -> list[HarnessSpec]:
        return [harness for harness in self.list(include_local=False) if harness.rank][:limit]

    def response(self) -> dict[str, Any]:
        return {
            "custom_harness_prefix": CUSTOM_HARNESS_PREFIX,
            "custom_harness_pattern": CUSTOM_HARNESS_RE.pattern,
            "harnesses": [asdict(harness) for harness in self.list()],
            "top_20": [asdict(harness) for harness in self.top(20)],
        }

    @staticmethod
    def _custom_harness(harness_id: str) -> HarnessSpec:
        name = harness_id.removeprefix(CUSTOM_HARNESS_PREFIX)
        return HarnessSpec(
            harness_id=harness_id,
            name=f"Custom Harness: {name}",
            category=HarnessCategory.CUSTOM,
            rank=None,
            provider="custom",
            runtime="caller-supplied",
            execution_contract="custom-harness.v1",
            repo_url=None,
            docs_url=f"local://cloud-agent-service/harnesses/{harness_id}",
            install_hint=(
                "provide a worker image or wrapper that knows how to execute this harness"
            ),
            env_requirements=[],
            strengths=[
                "custom integration point",
                "provider agnostic",
                "no registry change required",
            ],
            integration_notes=[
                "The service records and dispatches the harness contract.",
                "Execution requires a worker image or adapter that recognizes this harness ID.",
            ],
        )
